### ISSUE TITLE
对`RecyclerView#Adapter Wrapper`的多个修正

### ISSUE THREAD

**Issue by yanzhenjie** [hongyangAndroid/baseAdapter#110]
1. 更新Gradle版本，更新Support库版本为25.3.1。
2. `Adapter#bindViewHolder`支持`payloads`方式。
3. 修正`LoadMoreWrapper`文件名和类名不同。
4. 修改`addFootView()`为`addFooterView()`，并做`@deprecated` API兼容。
5. 重写几种`WrapperAdapter`中未重写的方法，作用是修正使用`ItemTouchHelper`拖拽Item时偶现viewType错误的问题。
Details: #109

**Comment by AIlll** [comment]
@yanzhenjie 请问下这个库如何设置数据并刷新适配器，调用super方法？

**Comment by dev3932** [comment]
看了下你提交修改的   adapter中3参数的调用了2参数的 
public void onBindViewHolder(VH holder, int position, List<Object> payloads) {
            onBindViewHolder(holder, position);
        }

**Comment by dev3932** [comment]
@AIlll 没有使用Wrapper相关类就直接adapter.notifyXXX相关方法,使用wrapper就 wrapper.notifyXXX相关方法
