### ISSUE TITLE
getItemViewDelegate判断

### ISSUE THREAD

**Issue by dwordwu** [hongyangAndroid/baseAdapter#41]
`public ItemViewDelegate getItemViewDelegate(T item, int position)
    {
        int delegatesCount = delegates.size();
        for (int i = delegatesCount - 1; i >= 0; i--)
        {
            ItemViewDelegate<T> delegate = delegates.valueAt(i);
            if (delegate.isForViewType(item, position))
            {
                return delegate;
            }
        }
        throw new IllegalArgumentException(
                "No ItemViewDelegate added that matches position=" + position + " in data source");
    }`
这个方法根据item以及position通过isForViewType判断是哪一个Delegate，但是如果有大于2种类型的话，isForViewType的返回值是布尔类型的，就不够用了。

**Comment by zj-wukewei** [comment]
你理解错了，这个是判断当前item的数据是不是属于当前delegate，当然只要布尔类型就搞定了啊，你没有看到他是通过遍历取出每个的delegate的，然后和当前item比较，看他是不是属于当前的delegate布局。

**Comment by dwordwu** [comment]
是的是的，是我的锅，开始理解错了！多谢
