### ISSUE TITLE
同时添加headview和emptyview,无法正确判断数据是否为空

### ISSUE THREAD

**Issue by YarenTang** [hongyangAndroid/baseAdapter#75]
同时添加headview和emptyview,无法正确判断数据是否为空。
断点发现  
```
private boolean isEmpty()
    {
        return (mEmptyView != null || mEmptyLayoutId != 0) && mInnerAdapter.getItemCount() == 0;
    }
```
ps:正常情况headview应该不算数据吧？吧？吧？..

**Comment by lalozhang** [comment]
这种情况可以嵌套wrapper使用，就OK了~比如：先new EmptyWrapper 然后在new HeaderAndFooterWrapper(emptyWrapper)。这样添加了header的同时且数据为空，会同时展示出header和emptyView
